- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - tmux
      - vim
      - tree
      - openjdk-8-jdk
      - gparted
      - nmap
      - make
